/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\hand_01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/hand_01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Basiccharacter" position={[0, -13.583, 0]}>
          <primitive object={nodes.clavicle_r} />
          <skinnedMesh name="BasiccharacterBody" geometry={nodes.BasiccharacterBody.geometry} material={materials['Basiccharacter:Body:Defaultskin']} skeleton={nodes.BasiccharacterBody.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hand_01.glb')
