/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\hand_02.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/hand_02.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Basiccharacter" position={[0, -13.583, 0]}>
          <primitive object={nodes.clavicle_r} />
          <group name="BasiccharacterHigh-poly" />
          <skinnedMesh name="BasiccharacterBody" geometry={nodes.BasiccharacterBody.geometry} material={materials['Basiccharacter:Body:Defaultskin']} skeleton={nodes.BasiccharacterBody.skeleton} />
        </group>
        <group name="Basiccharacter001" position={[0, -17.189, 0]}>
          <primitive object={nodes.clavicle_r_1} />
          <skinnedMesh name="BasiccharacterBody001" geometry={nodes.BasiccharacterBody001.geometry} material={materials['Basiccharacter:Body:Defaultskin']} skeleton={nodes.BasiccharacterBody001.skeleton} />
        </group>
        <group name="Basiccharacter002" position={[0, -10.969, 0]}>
          <primitive object={nodes.clavicle_r_2} />
          <skinnedMesh name="BasiccharacterBody002" geometry={nodes.BasiccharacterBody002.geometry} material={materials['Basiccharacter:Body:Defaultskin']} skeleton={nodes.BasiccharacterBody002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hand_02.glb')
